### ISSUE TITLE
Absolute path is used in the hooksDirectory setting in settings.json

### ISSUE THREAD

**Issue by AquilaSands** [Lakshmikanth2001/GitHooks#12] opened 2023-08-02 09:45 UTC
The hooksDirectory setting is using an absolute path in the workspace settings.json and as this file is normally committed to the repo it will cause a lot of unnecessary changes to this file for teams of devs or if you work across different devices e.g. Mac and Win.

**Comment by Lakshmikanth2001** [comment] 2023-08-02 09:56
yes this issue was previously addressed in #10 , I need to search for a function that can read `relative` path in node can you suggest one

**Comment by Lakshmikanth2001** [comment] 2023-08-03 07:19
Thanks @AquilaSands. In the latest release (i.e 91fd44859190d4228f7262a2020a0f4eae6bad1c v1.3.1), I figured out that we can use Node's `path.resolve` to get the relative directory. I have extended the support to input a relative path in the `GitHooks.HooksDirectory` settings. Please test it and give your valuable feedback. feel free to close the issue if every thing works for you thank you

**Comment by mpao** [comment] 2023-12-16 10:38
Hi there, there could have been another solution with

`"GitHooks.hooksDirectory": "${workspaceFolder}/.git/hooks"`

but every window reload the plugin overwrites this solution with the absolute path.
Now relative path works fine, not sure what is the better approach :)

**Comment by Lakshmikanth2001** [comment] 2023-12-16 17:12
@mpao In my Visual Studio Code extension, I've added code to handle relative directories up to two levels (. and ..). This is because the extension receives the expanded output of ${workspaceFolder}/.git/hooks, not the raw string. As a result, I lose the actual value entered by the user. Therefore, I encourage users to use relative directories to avoid this issue.

let me know if i can close this issue

**Comment by mpao** [comment] 2023-12-16 17:41
The issue is in the project `settings.json` file.

If you told me to use a relative path, I think I should use `../.git/hooks`  since the setting is the project's `.vscode` directory. Well, this is reported as wrong and overrided with the absolute path.

`.git/hooks` works great instead. I'm a new user of VSC and maybe I don't quite understand his behaviors, but seems than the issue is about documentation

**Comment by Lakshmikanth2001** [comment] 2023-12-17 08:04
ok i am closing this issue then as the relative path is working fine, thank you for your comments 😀

**Closed by Lakshmikanth2001** 2023-12-17 08:04 UTC
