### ISSUE TITLE
[BUG] Error running command git-hooks.reloadHooks: command 'git-hooks.reloadHooks' not found.

### ISSUE THREAD

**Issue by ionutz89** [Lakshmikanth2001/GitHooks#10] opened 2023-07-28 12:20 UTC
Hello,

I am getting this error:

```Error running command git-hooks.reloadHooks: command 'git-hooks.reloadHooks' not found. This is likely caused by the extension that contributes git-hooks.reloadHooks.```

I mentioned on configuration `Git Hooks: Hooks Directory` the full path.

Can you please let me know what I can do?

**Comment by Lakshmikanth2001** [comment] 2023-07-28 13:14
i encountered same bug when upgrading from `1.0.` to `1.1` just restart your vscode or using `Developer: Reload Windows` to refresh the vscode instance that automatically resolved the issue please let me know if this works for you

**Comment by ionutz89** [comment] 2023-07-28 14:03
I tried @Lakshmikanth2001, your suggestion, without any luck. I am using VS under OS macOS.

Anything else that I should try it?

**Comment by ionutz89** [comment] 2023-07-28 14:05
When I tried to refresh the Hooks button: I got this error:

```Error running command git-hooks.toggleView: command 'git-hooks.toggleView' not found. This is likely caused by the extension that contributes git-hooks.toggleView.```

**Comment by Lakshmikanth2001** [comment] 2023-07-28 15:41
ok I am unable to reproduce the issue on `Mac` you can uninstall and install the extension back for the latest version may be some extension caching issue, you can help by inspecting the `extensionHost` logs under `output` tab, mostly reinstalling the extension should resolve the issue please let me know if it works

**Comment by ionutz89** [comment] 2023-07-30 07:26
It seems it does not like this format path: `~/.hooks`


I had to update this version in settings VS:
`~/Users/username/.hooks`

**Comment by Lakshmikanth2001** [comment] 2023-07-30 09:00
yes you are right you should give absolute path as I am using `node's` path library to read the file system, let me know if I can close this issue

**Closed** 2023-07-30 09:26 UTC
Labels: bug
